version: '3'
services:
  webapp:
    container_name: api-invillia
    build: 
      context: ./backend/GameLoanApi
      dockerfile: api.Dockerfile
    ports:
      - 5000:80
    links:
      - mysql
   
  mysql:
    container_name: db-invillia
    build:
      context: ./db
      dockerfile: db.dockerfile
    ports:
      - 3306:3306 
    restart: always
    volumes:
      - dbvol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: invillia@rootPass
      MYSQL_DATABASE: invillia
      MYSQL_USER: invillia
      MYSQL_PASSWORD: invillia@legal

volumes:
  dbvol: